# Generated by Django 4.1.7 on 2024-05-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_products_company'),
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bought',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributor.products'),
            preserve_default=False,
        ),
    ]
