# Generated by Django 4.1.7 on 2024-05-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0002_bought_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('totalprice', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=30)),
                ('buyer', models.CharField(max_length=30)),
            ],
        ),
    ]
