# Generated by Django 3.2.25 on 2024-05-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
