# Generated by Django 4.1.7 on 2024-05-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='company',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
